### ISSUE TITLE
Crypto Go ：we are a research group to help developers build secure applications.

### ISSUE THREAD

**Issue by 1047261438** [FUSIONFoundation/efsn#71]
Hi, we are a research group to help developers build secure applications. We designed a cryptographic misuse detector (i.e., CryptoGo) on Go language. We found your great public repository from Github, and several security issues detected by CryptoGo are shown in the following. 
Note that the cryptographic algorithms are categorized with two aspects: security strength and security vulnerability based on NIST Special Publication 800-57 and other public publications. Moreover, CryptoGo defined certain rules derived from the APIs of Go cryptographic library and other popular cryptographic misuse detectors. The specific security issues we found are as follows:
(1)	Location: accounts/keystore/keystore_passphrase.go:330
Broken rule: the salt of scrypt is not random;
(2)	Location: accounts/keystore/presale.go:77
Broken rule: the salt of pbkdf2 is constant;
(3)	Location: crypto/ecies/ecies.go:204
Broken rule: R-04: Not unique IV in CTR;
(4)	Location: signer/storage/aes_gcm_storage.go:133
Broken rule: Constant key in AES;
 We wish the above security issues could truly help you to build a secure application. If you have any concern or suggestion, please feel free to contact us, we are looking forward to your reply. Thanks.

**Comment by fanbsb** [comment]
Thanks for the issue detection work. Let me explain the issue one by one below.

1. (1) Location: accounts/keystore/keystore_passphrase.go:330
Broken rule: the salt of scrypt is not random;

Answer: the salt is reading from the keystore file, so it's depend on each keystore file, not fixed value

(2) Location: accounts/keystore/presale.go:77
Broken rule: the salt of pbkdf2 is constant;

Answer: the salt is same as the password, since password is not constant, salt is not constant as well.

(3) Location: crypto/ecies/ecies.go:204
Broken rule: R-04: Not unique IV in CTR;

Answer: the value of IV is generate from method generateIV(params, rand), which the parameter rand is a random reader from outside.

(4) Location: signer/storage/aes_gcm_storage.go:133
Broken rule: Constant key in AES;

Answer: the key is passed from parameter outside, which is not constant value.
